all: server service

server: servidorhttp.c servidor.c servidor.h 
	gcc servidorhttp.c servidor.c servidor.h -o server

service: serviciohttp.c servicio.c servicio.h 
	gcc serviciohttp.c servicio.c servicio.h -o service


